### ISSUE TITLE
go get cmd returns missing header file

### ISSUE THREAD

**Issue by agaviria** [augustoroman/v8#1]
Hi there, thanks for this library.  I just tried to go get and the compiler returns missing 'libplatform.h' file not found.  I attempted to attach a darwin 10.11, x64.release libplatform header to this thread but github does not support this filetype.  Let me know if you would like me to email it or if you prefer a pull request.  I'm not sure if you find it useful to include it to this package.

**Comment by agaviria** [comment]
Actually, I just realized after reading the README that this warning is superfluous because files will vary depending on your architecture build.   As the readme states, this is where include and libv8 folders would be symlinked as part of $GO_V8 path.  Please disregard my previous comment.

**Comment by augustoroman** [comment]
Thanks.  Did you get it working?  Or is the README not sufficiently clear?

**Comment by agaviria** [comment]
@augustoroman Yep, is working.  Thank you.
