### ISSUE TITLE
Simplify Bind example to clearly demonstrate bind.

### ISSUE THREAD

**Issue by flowchartsman** [augustoroman/v8#12]
It actually uses `create`'s automatic binding and then `set`.

**Comment by augustoroman** [comment]
Updated in https://github.com/augustoroman/v8/commit/ddd1698eed1405f97f66dcd5df0d3739e138f13e

Please let me know if that improves the situation.

**Comment by augustoroman** [comment]
Thanks!  I'll remove that tonight.
