### ISSUE TITLE
Undefined symbol v8::ArrayBuffer::Allocator

### ISSUE THREAD

**Issue by jeromegn** [augustoroman/v8#14]
```
$ go test
# github.com/augustoroman/v8
Undefined symbols for architecture x86_64:
  "typeinfo for v8::ArrayBuffer::Allocator", referenced from:
      typeinfo for ArrayBufferAllocator in _x004.o
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL	github.com/augustoroman/v8 [build failed]
```

If I check the symbols with `nm -g`, I found:

```
0000000000035500 T __ZN2v811ArrayBuffer9AllocatorD0Ev
00000000000354f0 T __ZN2v811ArrayBuffer9AllocatorD1Ev
```

I've been using pre-compiled versions of v8: https://rubygems.org/gems/libv8

I guess it's not finding the symbol because it's mangled? I thought this was handled somehow via the bridge.

Is the pre-compiled v8 at fault here? I dreaded compiling it myself because of how time consuming it is.

**Comment by jeromegn** [comment]
I figured it out.

For posterity: You need to run this with the compiler option `-fno-rtti` I added it to v8.go locally and it worked for me. Even with the static v8 build.

**Comment by augustoroman** [comment]
Thanks.  What version of go, gcc/clang, and OS platform are you on?

**Comment by augustoroman** [comment]
also, did you modify both v8.go and v8_client.go?  or just one of them?

**Comment by jeromegn** [comment]
go 1.10 darwin amd64, clang 5.0.1

I only modified v8.go.

The tests are passing except for:

```
=== RUN   ExampleContext_Bind
--- FAIL: ExampleContext_Bind (0.29s)
got:
hello.js:2> Hello World!
hello.js:3> function () { return "x" }
hello.js:4> 1,2,3
want:
hello.js:2> Hello World!
hello.js:3> function() { return "x" }
hello.js:4> 1,2,3
```

**Comment by jeromegn** [comment]
I highly recommend the libv8 ruby gem if you want to test on multiple platforms without having to rebuild v8 on travis :) Works like a charm. Unfortunately the latest is only 6.3.x.

**Comment by augustoroman** [comment]
That last test looks like gofmt spacing changes. :-/

**Comment by augustoroman** [comment]
thanks, that's a good idea!  If you feel adventurous, I'd be happy to take a PR for the travis conversion, otherwise I'll look into that when I get the time.

**Comment by augustoroman** [comment]
I'm still confused about why you had that error even when compiling v8 yourself, though. I've had no problems on a mac. :-/

**Comment by jeromegn** [comment]
It's doing the same thing if I build it with Docker (with a Debian Stretch image.) I have to specify the custom `CGO_CXXFLAGS` to build.

The good news is: the same process (download the right libv8 gem and symlink) works with Linux.

I had issues with Alpine (missing ELF header or something), but it could be due to musl or something.

I'm happy to streamline the Travis build, but I'm hesitant to use these bindings because of some missing features. I think I'd be able to add some, but not all due to my limited C++ knowledge. For instance, I think I can add HeapStatistics (I've done it in a fork a few months ago), but I doubt I could add a way to define "native" constructors (function templates I think.)
