### ISSUE TITLE
How to cross compile projects using it?

### ISSUE THREAD

**Issue by prsolucoes** [augustoroman/v8#32]
Hi,

How to cross compile projects using it?

I have a project GoHC (https://github.com/prsolucoes/gohc) that use old javascript implementation in go.

Can i cross compile my project using your library or i need a linux/windows/arm machine to compile their version?

Thanks.

**Comment by augustoroman** [comment]
I have compiled this code on a mac and linux, but I've never successfully gotten it working on windows or arm.  I have never cross-compiled it.  You could try https://github.com/karalabe/xgo or some other cross compiler.  There are also pure-go javascript interpreters like https://github.com/dop251/goja or https://github.com/robertkrimen/otto which would cross-compile easier but may not be quite as performant if you are running large amounts of javascript.
