### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by bigblind** [augustoroman/v8#35]
I'm segmentation faults on in various situations. I'm still trying to create the smallest test case that exhibits the problem, but so far, I've been unsuccessful.

I'm eval'ing the following code:

```
 marvin = {
    _triggers: [],
    _inputs: [],
    _inputValues: {
        
    },
    _inputsSeen: {},
    isSetup: true
};

marvin._runAction = (provider, groupp, name, input) => {
        if(marvin.isSetup){
            throw new Error(`Can't call an action: ${provider}.${group}.${name}, during setup.`);
        }
        return _runAction(provider, group, name, input);
};

marvin.input = (name, description) => {
    if(!marvin._inputsSeen[name]){
        marvin._inputs.push({name, description});
        marvin._inputsSeen[name] = true;
    }
    return marvin._inputValues[name];
};


http = {};
http.request = {};
http.request.send = (input) => marvin._runAction("http", "request", "send", input);

time = {};
time.cron = {};
 time.cron.schedule = (input, callback) => marvin._triggers.push({
     provider: "time",
     group: "cron",
     action: "schedule",
     input: input,
     callback: callback
 });
time.cron.nextScheduledTime = (input) => marvin._runAction("time", "cron", "nextScheduledTime", input);
        
time.cron.schedule({expression: "0-59/10 * * * * * *"}, (result) => {
    return doesNotExist;
});
marvin.isSetup=false;
marvin._triggers[0].callback(__triggeredEvent) 
```

I've cleaned up some of the whitespace in this code a bit when posting it here, because it's generated using a Go template. I know it's quite long, but I haven't managed to write a shorter piece of js that triggers the same behaviour.

The context is created like this:

```go
func (c *Chore) CreateContext() *v8.Context {
	is := v8.NewIsolate()
	jsCtx := is.NewContext()

	runAction := jsCtx.Bind("_runAction", func(args v8.CallbackArgs) (*v8.Value, error) {
		provider := args.Arg(0).String()
		group := args.Arg(1).String()
		action := args.Arg(2).String()

		a, err := actions.Registry.GetAction(provider, group, action)
		if err != nil {
			return nil, err
		}

		inBytes, err := args.Arg(3).MarshalJSON()
		if err != nil {
			return nil, err
		}

		in := reflect.New(reflect.TypeOf(a.Info().InputType)).Interface()
		err = json.Unmarshal(inBytes, in)
		if err != nil {
			return nil, err
		}

		out, err := a.Run(in, context.Background())
		if err != nil {
			return nil, err
		}

		return jsCtx.Create(out)
	})
	jsCtx.Global().Set("_runAction", runAction)

	cons := v8console.Config{Stdout: os.Stdout, Stderr: os.Stderr}
	cons.Inject(jsCtx)

	return jsCtx
}

// And in the function that executes the code:
eventValue, err := jsCtx.Create(value)
if err != nil {
	// ...
}

err = jsCtx.Global().Set("__triggeredEvent", eventValue)
if err != nil {
	//...
}

go func() {
		code := c.getJS()
		fmt.Println("CODE:\n\n", code)
		res, err := jsCtx.Eval(code, "name.js")
		fmt.Println("result:", res, " error:", err)
	}()
```

When I run this code, I get:

```
==== C stack trace ===============================

[end of stack trace]
Segmentation fault: 11
```

There's nothing in the stack trace.

if I change `return doesNotExist` for something like `return 5*5`, it works correctly, so I thought there was a problem with handling ReferenceErrors, but I tried creating a small test case with code that causes a reference error, both in the global scope and inside a function, and none of them cause a segmentation fault.

I also got a segmentation fault when I tried creating a context from an isolate that was created with a snapshot of the JS code above, except the 2 last lines.

Let me know if you need any other information. I've never worked with C or C++, so I'm not really sure how to debug this.

**Comment by inge4pres** [comment]
Hi @bigblind 
for what I've seen in the couple of hours using this lib, that error indicates mainly a syntax error in your JS code.
Have you tried running that in another runtime out of this project?

**Comment by bigblind** [comment]
The main time it seems to happen for me, is when another goroutine is using
time.sleep. Eliminating that solved the problem for me.

**Comment by bigblind** [comment]
I've eliminated time.Sleep, and everything works for me now.
