### ISSUE TITLE
Please issue a tag so to be imported in go modules 

### ISSUE THREAD

**Issue by inge4pres** [augustoroman/v8#36]
Hi :)

thanks for your work on this, could you please add a tag on this repository with a semantic version?
Ideally `v0.0.1` or `v0.1.0`. Anything that could allow this project to be used as a library using go modules.
Thank you
Regards

**Comment by augustoroman** [comment]
Sorry for the delay.  `v1.0.0` tag has been pushed -- the API should be stable, any breaking changes will bump the major version.

**Comment by TheSchemm** [comment]
One thing I wish to add is that if you are using modules, getting the package `github.com/augustoroman/v8` will cause an error because Go tries to interpret that as version 8 of augustoroman. In order to get around this I have to use 'gopkg.in/augustoroman/v8.v1'
