### ISSUE TITLE
libplatform/libplatform.h not found

### ISSUE THREAD

**Issue by base698** [augustoroman/v8#46]
After running the install steps in the readme.md it fails libplatform/libplatform.h not found and does the same for go test.

```
$ go test
# github.com/augustoroman/v8
v8_c_bridge.cc:3:10: fatal error: libplatform/libplatform.h: No such file or directory
 #include "libplatform/libplatform.h"
```

**Comment by base698** [comment]
@augustoroman I am getting this again.  I don't remember what I did to fix it.  Can you `find include` and `libv8`?  Is there some kind of environment var I need to set I didn't?  I'm doing the docker directions exactly.  Do you need to create **include** and **libv8** before running `docker cp`?

**Comment by base698** [comment]
Figured it out.  Here is the find from my working machine in case anyone has the issue.

```
$ find include/
include/
include/libplatform
include/libplatform/v8-tracing.h
include/libplatform/DEPS
include/libplatform/libplatform-export.h
include/libplatform/libplatform.h
include/v8-inspector-protocol.h
include/v8-inspector.h
include/v8-testing.h
include/v8config.h
include/v8-value-serializer-version.h
include/v8-profiler.h
include/v8-util.h
include/v8-platform.h
include/include
include/DEPS
include/v8.h
include/PRESUBMIT.py
include/APIDesign.md
include/v8-version.h
include/OWNERS
include/v8-version-string.h

$ find libv8/
libv8/
libv8/libv8_base.a
libv8/libv8_libsampler.a
libv8/libv8_libplatform.a
libv8/libv8_init.a
libv8/libv8_libbase.a
libv8/libv8_nosnapshot.a
libv8/libv8_initializers.a

```

**Comment by smrangel** [comment]
Yo estoy incrustando el motor v8 en un proyecto de c++, tengo el mismo problema cuando incluyo las librerias dentro de mi proyecto.
