### ISSUE TITLE
Can I handle HTML DOM with this v8-API?

### ISSUE THREAD

**Issue by eaglexiang** [augustoroman/v8#49]
I tried to import dom.js and jquery.js, but both didn't work well.

Is there some good way to operate DOM with style in browser console? such as `create DOM from HTML string` or `analysis HTML with jquery $`.

**Comment by augustoroman** [comment]
No, sorry. There's no associated DOM with the v8 javascript engine.

I'm not familiar with dom.js, but jquery.js certainly won't work since that's designed to operate in a browser environment where the browser code adds the DOM into the JS engine environment.
