### ISSUE TITLE
Cannot find -ldl

### ISSUE THREAD

**Issue by Zentendo** [augustoroman/v8#5]
I keep getting:

```
# github.com/augustoroman/v8
/usr/bin/x86_64-w64-mingw32-ld: cannot find -ldl
/usr/bin/x86_64-w64-mingw32-ld: cannot find -ldl
collect2: error: ld returned 1 exit status
```

On crosscompling on 64 bit Ubuntu linux with MinGW and as well as MinGW directly on Windows, with both linux built binaries and windows built .lib tried in the include/ld flags. 

I searched in the v8 directory generated by depot_tools and I've also tried building several versions of node which have v8 versions between 54 - 60 but none of them contain a `dl.lib`  on out directory. What am I supposed to be looking for? I don't need `dl` to compile when targeting native linux.

Cross-compiling is working for other libraries, it works with these bindings as well on linux (without crosscompiling). But both crosscompiling this go lib with linux and using MinGW directly on Windows with MSYS installed and windows built .lib binaries for v8 always returns `"cannot find -ldl"`.

[Culprit line.](https://github.com/augustoroman/v8/blob/04477baf810a8096f63a9f9be5901a7302050648/v8_create.go#L18)

```
// #cgo CXXFLAGS: -I${SRCDIR} -I${SRCDIR}/include -std=c++11
// #cgo LDFLAGS: -L${SRCDIR}/libv8 -lv8_base -lv8_libbase -lv8_snapshot -lv8_libsampler -lv8_libplatform -ldl -pthread
```

What am I missing here?

**Comment by augustoroman** [comment]
Sorry that this languished.  I'm closing due to age and the fact that the build instructions have changed substantially recently.  Please re-open if you still have problems.
